### ISSUE TITLE
error - pineconeclient project name not set

### ISSUE THREAD

**Issue by wweevv-johndpope** [fraserxu/book-gpt#10]
https://book-gpt.vercel.app/credentials
i did the instructions - pine cone boots up - 
<img width="1654" alt="Screenshot 2023-03-03 at 11 34 43 pm" src="https://user-images.githubusercontent.com/109928647/222721525-686c1e66-e4b1-471c-8756-95032e3376b9.png">

**Comment by wweevv-johndpope** [comment]
- thanks

**Comment by wweevv-johndpope** [comment]
maybe even if it ever throws this error and detects  - just word the instructions in the error message.

**Comment by wweevv-johndpope** [comment]
I think there's an upload pdf size limit too - 
I mistakingly tried to upload a 21mb file that was for controlnet - didn't need so much of that.

**Comment by wweevv-johndpope** [comment]
<img width="1854" alt="Screenshot 2023-03-03 at 11 58 28 pm" src="https://user-images.githubusercontent.com/109928647/222726187-d2bd9506-14c8-4471-9f62-65a49008510d.png">

that's weird - I deleted and recreated with correct name - but no joy.

maybe it's the pdf - 
https://drive.google.com/file/d/1t0qU-2BKJIC2YkYn9jKHAkNfYkNYNrlg/view?usp=share_link

**Comment by fraserxu** [comment]
Not sure if it's because of the pdf file, I upgrade the dep here and tried with your pdf and it works for me.


<img width="1368" alt="CleanShot 2023-03-04 at 11 45 42@2x" src="https://user-images.githubusercontent.com/1183541/222862470-b7a93439-d079-4d62-bfc7-e04dee1a2bee.png">

**Comment by fraserxu** [comment]
I deployed the change, please give it a try and let me know if you still have issues.
