### ISSUE TITLE
something went wrong

### ISSUE THREAD

**Issue by johndpope** [fraserxu/book-gpt#13]
<img width="1033" alt="Screenshot 2023-03-06 at 4 42 54 pm" src="https://user-images.githubusercontent.com/289994/223035408-3b014f0b-09b0-4a7c-9729-7912483c775f.png">

<img width="2418" alt="Screenshot 2023-03-06 at 5 29 21 pm" src="https://user-images.githubusercontent.com/289994/223035457-8607f98a-fd4b-4f76-99ad-416c567ccb22.png">

it would help me if this error was actually returned in the client - rather than having to debug app. 
'PineconeClient: Error calling upsert: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response  '

**Comment by Klaudioz** [comment]
Happening the same to me with certain PDFs files. Actually, I did a test and divided that big PDF into one-page size PDFs and I tried with each of them and I didn't have any issues. Unfortunately, the description of the Pinecone issue is very poor.

**Comment by johndpope** [comment]
I think there's no attribute message e.message - the error is "e" object.

**Comment by fraserxu** [comment]
Thanks @Klaudioz @johndpope do you know a way to reproduce this consistently? Happy to handle this case to provide a better error feedback.

**Comment by Klaudioz** [comment]
Please send me a PM on Twitter (https://twitter.com/klaudioz) to share the file with you.

**Comment by BaileySimrell** [comment]
Not sure if related as this one is showing an explicit error message, but I'm experiencing this on my end: 

<img width="432" alt="Screenshot 2023-03-07 at 11 43 50" src="https://user-images.githubusercontent.com/6186817/223490236-a8e1a052-a939-469f-89e3-9e91474f8b44.png">

Followed everything exactly as outlined

**Comment by fraserxu** [comment]
This error is usually because the the client is not able to find the index created under the account, can you double check the followings:
* index name is `book-gpt`
* index region is in `us-west1-gcp` (I will make this configurable in the future)

cc @BaileySimrell

**Comment by johndpope** [comment]
thanks for troubleshooting - after updating env to us-east - I finally get upload success callback.
This popped up on my radar - maybe useful 
https://github.com/johndpope/PatrikZeros-ChatGPT-API-UI

**Comment by BaileySimrell** [comment]
Nevermind, I see this was hard-coded in. Finally got it working on my end!

To anybody seeing this, just make sure you change the environment to `us-east1-gcp` or whatever your specific region is in both `pages/api/ingest.ts` AND `pages/api/chat.ts`

Great work @fraserxu and thanks for your help troubleshooting as well @johndpope!

**Comment by fraserxu** [comment]
@Klaudioz I tried your provided pdf and can reproduce the issue. I was able to get better error response after upgraded the `pinecone` npm package thanks to @rschwabco 's recent work on better error handling.

```
[Error: PineconeClient: Error calling upsert: Error: Your request is larger than the maximum supported size - 2MB. Please try to reduce your batch size.]
```

A short term fix is maybe try to cut the pdf manually by yourself. I'll be looking at if I can do this with code or maybe adjust batch size or something in the next few days.

**Comment by Klaudioz** [comment]
Thanks for your answer. That limitation sounds weird to me. I've uploaded bigger files in the past without any issues.

I'd really like to know where that limitation is mentioned in Pinecone's documentation.

I'm going to update the Pinecone package right now!!

**Comment by fraserxu** [comment]
https://github.com/pinecone-io/pinecone-ts-client/issues/23

**Comment by fraserxu** [comment]
@johndpope @Klaudioz while we waiting for the issue being clarified by the upstream, I've implemented a simple chunk function which would write the doc in to pinecone with small chunks.

I tested with the PDF @Klaudioz provided and can query fine. Please let me know if it works for you, cheers.
