### ISSUE TITLE
Pinecone environment is hardcoded and  users based out of West Coast cannot use the app

### ISSUE THREAD

**Issue by Nailan** [fraserxu/book-gpt#19]
The problem is that in Pinecone I couldn't find an option to pick environment and every index I create has "us-east-1-aws" environment. So the application throws an error:
> PineconeClient: Error getting project name: SyntaxError: Unexpected token 'A', "API key is"... is not valid JSON

To fix this problem I moved Pinecone environment to credentials (the same way you do with API keys). How can I create a pull request with this fix?

**Comment by fraserxu** [comment]
It will be another field in the credentials form, or maybe two, one for the index name and one for region. 

This can be added to https://github.com/fraserxu/book-gpt/blob/main/pages/credentials.tsx

**Comment by Nailan** [comment]
@fraserxu Yes, I mean if you changed your security settings I could create a PR with the fix

**Comment by fraserxu** [comment]
Hmm, sorry if I missed anything, can you fork this repo and create pull request?

**Comment by Nailan** [comment]
Sure, I can do that
Thanks
